# Generated by Django 5.1.6 on 2025-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
